"use client";

import React, { useEffect, useState } from "react";
import BackLink from "@/components/BackLink";
import NotificationProfile from "@/components/NotificationProfile";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, Eye, Download, FileText } from "lucide-react";
import Image from "next/image";
import { useParams } from "next/navigation";
import { fetchWithAuth } from "@/components/utils/fetchwitAuth";
import { PDFDocument, rgb } from 'pdf-lib'; // Import PDF generation library

export default function Page() {
  const { userId } = useParams();
  const [userData, setUserData] = useState(null);
  const [error, setError] = useState(null);

  // Fetch user data
  useEffect(() => {
    const fetchUserData = async () => {
      try {
        const response = await fetchWithAuth(
          `https://mojoapi.grandafricamarket.com/api/users/${userId}`
        );
        if (!response.ok) throw new Error(`Error: ${response.statusText}`);
        const data = await response.json();
        setUserData(data.user); // Accessing the `user` object inside the response
      } catch (err) {
        console.error("Failed to fetch user data:", err);
        setError("Failed to load user data.");
      }
    };

    if (userId) {
      fetchUserData();
    }
  }, [userId]);


  // Add these functions to handle view and download actions
  const handleView = async () => {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 400]);
  
    // Header
    page.drawRectangle({
      x: 0,
      y: 400,
      width: 600,
      height: 60,
      color: rgb(0.2, 0.4, 0.6), // Header background color
    });
    page.drawText('User Details', {
      x: 50,
      y: 420,
      size: 30,
      color: rgb(1, 1, 1), // White text color
    });
  
    // Add a line for separation
    page.drawLine({ start: { x: 50, y: 390 }, end: { x: 550, y: 390 }, color: rgb(1, 1, 1), thickness: 2 });
  
    // Add user details with improved formatting
    const details = [
      { label: 'First Name', value: userData.first_name },
      { label: 'Last Name', value: userData.last_name },
      { label: 'Email', value: userData.email },
      { label: 'Phone', value: userData.phone },
      { label: 'Status', value: userData.status || 'Active' },
    ];

    let yPosition = 350; // Starting position for details
    details.forEach(detail => {
      page.drawText(`${detail.label}:`, { x: 50, y: yPosition, size: 1, color: rgb(0, 0, 0) });
      page.drawText(detail.value, { x: 200, y: yPosition, size: 1, color: rgb(0, 0, 0) });
      yPosition -= 30; // Move down for the next detail
    });
  
    // Footer
    page.drawText('Generated by Mojo Money Transfer', {
      x: 50,
      y: 30,
      size: 12,
      color: rgb(0.5, 0.5, 0.5), // Gray text color
    });
  
    const pdfData = await pdfDoc.save();
    const pdfUrl = URL.createObjectURL(new Blob([pdfData], { type: 'application/pdf' }));
    window.open(pdfUrl, '_blank');
  };
  
  const handleDownload = async () => {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 400]);
  
    // Header
    page.drawRectangle({
      x: 0,
      y: 400,
      width: 600,
      height: 60,
      color: rgb(0.2, 0.4, 0.6), // Header background color
    });
    page.drawText('User Details', {
      x: 50,
      y: 420,
      size: 30,
      color: rgb(1, 1, 1), // White text color
    });
  
    // Add a line for separation
    page.drawLine({ start: { x: 50, y: 390 }, end: { x: 550, y: 390 }, color: rgb(1, 1, 1), thickness: 2 });
  
    // Add user details with improved formatting
    const details = [
      { label: 'First Name', value: userData.first_name },
      { label: 'Last Name', value: userData.last_name },
      { label: 'Email', value: userData.email },
      { label: 'Phone', value: userData.phone },
      { label: 'Status', value: userData.status || 'Active' },
    ];
  
    let yPosition = 350; // Starting position for details
    details.forEach(detail => {
      page.drawText(`${detail.label}:`, { x: 50, y: yPosition, size: 10, color: rgb(0, 0, 0) });
      page.drawText(detail.value, { x: 200, y: yPosition, size: 10, color: rgb(0, 0, 0) });
      yPosition -= 30; // Move down for the next detail
    });
  
    // Footer
    page.drawText('Generated by Mojo Money Transfer', {
      x: 50,
      y: 30,
      size: 12,
      color: rgb(0.5, 0.5, 0.5), // Gray text color
    });
  
    const pdfData = await pdfDoc.save();
    const pdfUrl = URL.createObjectURL(new Blob([pdfData], { type: 'application/pdf' }));
    
    const link = document.createElement('a');
    link.href = pdfUrl;
    link.setAttribute('download', 'user_details.pdf'); // Specify the file name
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  if (error) {
    return <p className="text-red-500 text-center">{error}</p>;
  }

  if (!userData) {
    return <p className="text-center text-gray-500">Loading...</p>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="flex items-center justify-between p-4 bg-white border-b">
        <h1 className="text-xl font-semibold text-primary">User Management</h1>
        <div className="flex items-center gap-4">
          <NotificationProfile
            profileLink="/agent-dashboard/settings"
            notificationLink="/agent-dashboard/notifications"
          />
          <div className="h-8 w-8 rounded-full bg-gray-200 overflow-hidden">
            <Image
              src="/placeholder.svg?height=32&width=32"
              alt="Profile"
              width={32}
              height={32}
              className="object-cover"
            />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="p-4 max-w-4xl mx-auto">
        <div className="mb-6">
          <BackLink>
            <ArrowLeft className="h-4 w-4" />
            View User - {userData.first_name} {userData.last_name}
          </BackLink>
        </div>

        <Card>
          <CardContent className="p-6">
            <h2 className="text-lg font-semibold mb-6">View Information</h2>

            <div className="grid grid-cols-2 gap-x-8 gap-y-6">
              <div>
                <p className="text-sm text-muted-foreground mb-1">First Name</p>
                <p className="font-medium">{userData.first_name}</p>
              </div>

              <div>
                <p className="text-sm text-muted-foreground mb-1">Last Name</p>
                <p className="font-medium">{userData.last_name}</p>
              </div>

              <div>
                <p className="text-sm text-muted-foreground mb-1">Email</p>
                <p className="font-medium">{userData.email}</p>
              </div>

              <div>
                <p className="text-sm text-muted-foreground mb-1">Phone no.</p>
                <p className="font-medium">{userData.phone}</p>
              </div>

              <div>
                <p className="text-sm text-muted-foreground mb-1">Date</p>
                <p className="font-medium">
                  {userData.created_at
                    ? new Date(userData.created_at).toLocaleDateString(
                        "en-US",
                        {
                          month: "long",
                          day: "numeric",
                          year: "numeric",
                        }
                      )
                    : "N/A"}
                </p>
              </div>

              <div>
                <p className="text-sm text-muted-foreground mb-1">Status</p>
                <p className="font-medium">{userData.status || "Active"}</p>
              </div>

              <div className="col-span-2 pt-4">
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-white rounded">
                      <FileText className="h-6 w-6 text-blue-600" />
                    </div>
                    <div>
                      <p className="font-medium">ID.PDF</p>
                      <p className="text-sm text-muted-foreground">320 KB</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <p className="text-sm text-muted-foreground">12/2/2024</p>
                    <Button variant="ghost" size="icon" onClick={() => handleView()}>
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleDownload()}>
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
