import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { DM_Sans } from "next/font/google";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const dmSans = DM_Sans({
  subsets: ["latin"], // Specify subsets (optional)
  weight: ["400", "500", "700"], // Specify weights (optional)
  style: ["normal", "italic"], // Specify styles (optional)
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${dmSans} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
